name: Cloudflare DDNS Update

on:
  schedule:
    - cron: "*/5 * * * *"  # 每5分钟运行一次
  workflow_dispatch:       # 允许手动触发

env:
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  ZONE_ID: ${{ secrets.CF_ZONE_ID }}
  RECORD_NAME: ${{ secrets.CF_RECORD_NAME }}
  CF_TTL: ${{ secrets.CF_TTL }}
  CF_PROXIED: ${{ secrets.CF_PROXIED }}

jobs:
  update-ddns:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: 运行 DDNS 更新脚本
        run: |
          python cloudflare-ddns.py
